export enum Color {
  default = 'default',
  primary = 'primary',
  wrarning = 'warning',
  danger = 'danger',
  secondary = 'secondary',
  info = 'info',
  success = 'success',
  light = 'light',
  dark = 'dark',
  outline_primary = 'outline-primary',
  outline_default = 'outline-default',
  outline_wrarning = 'outline-warning',
  outline_danger = 'outline-danger',
  outline_secondary = 'outline-secondary',
  outline_info = 'outline-info',
  outline_success = 'outline-success',
  outline_light = 'outline-light',
  outline_dark = 'outline-dark',
}
